### PR TITLE
Add strongnames using key from Nito.AsyncEx v4

### PR DESCRIPTION
**Pull request by Alexx999**
Well, it's pretty much in the title. Add strongnames for all the desktop developers out there :)

### CODE REVIEW

**Comment by StephenCleary** [comment]
I'm planning a different approach for strong-naming on these libraries. And I'll never strong-name in the main package due to all the problems caused by strong-naming.

**Comment by dittodhole** [comment]
Sorry for coming back on this very old thread, but did you have a look at the Microsoft guidance for open-source libraries regarding strong naming?
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming

**Comment by StephenCleary** [comment]
Yes. That's easy for them to say, but the tooling issues remain the same. Microsoft is not investing any more in strong naming, since it is a dead technology. So the tooling is still insufficient and likely to remain so indefinitely.

I could work around the lack of proper tooling by writing my own tooling, but:
1. People will care less about this over time, since strong naming is ignored on modern .NET.
2. I just have too much other work to do.

So, I apologize for the trouble, but I'm still not planning to implement strong naming.

**Comment by dittodhole** [comment]
Strong-naming is mainly used for compliance reasons nowadays, to give an identity guarantee.

Some admin deps/industry partners are constantly evolving their policies (i.e. create a fully identified and signed chain), hence I've asked for your thoughts on this matter.

Anyway, would you mind if I repackage your sources internally (following the MIT licence) to build such a trust chain?

**Comment by StephenCleary** [comment]
> Strong-naming is mainly used for compliance reasons nowadays, to give an identity guarantee.

IMO this is one of the biggest problems with strong-naming: the guarantees it provides are useless for security. Strong-naming only means someone signed it, not that someone specific signed it. And, of course, on modern .NET, it means *nothing at all*.

Authenticode signing would be reasonable to adopt as a security policy. Strong-name signing is just security theater.

> would you mind if I repackage your sources internally (following the MIT licence) to build such a trust chain?

Not at all! Feel free! Just please don't publish it on NuGet.

**Comment by dittodhole** [comment]
> > Strong-naming is mainly used for compliance reasons nowadays, to give an identity guarantee.
> 
> IMO this is one of the biggest problems with strong-naming: the guarantees it provides are useless for security. Strong-naming only means someone signed it, not that someone specific signed it. And, of course, on modern .NET, it means _nothing at all_.

Additional code-signing set up on my side for exactly this reason, but with strong-naming assembly bindings would be way more easier to handle.

> > would you mind if I repackage your sources internally (following the MIT licence) to build such a trust chain?
> 
> Not at all! Feel free! Just please don't publish it on NuGet.

👍 my sentiments exactly

**Pull request closed without merging**
